### ISSUE TITLE
Symphony 2.6

### ISSUE THREAD

**Issue by timokleemann** [nils-werner/sass_compiler#1]
Has anyone ever tried this under Symphony 2.6?

I can't get it working...

**Comment by nils-werner** [comment]
I am not working with PHP and Symphony anymore so I don't have a testbed to fix it. Would you like to take over ownership of the extension? :-)

**Comment by timokleemann** [comment]
I would love to but my PHP skills aren't good enough. I would be willing to make a donation though if anyone could get this to work with Symphony 2.6 and higher.

**Comment by timokleemann** [comment]
OK, problem solved. 

In `/sass_compiler/lib/sass.php` replace this line:

```
require_once(DOCROOT . '/symphony/lib/boot/bundle.php');
```

with this:

```
require_once(DOCROOT . '/vendor/autoload.php');
```

Also make sure you have the `vendor` folder. Older versions of Symphony don't have it.

This will make the extension work with Symphony 2.6 (and probably above).

**Comment by nils-werner** [comment]
Can you send a PR with a fix? Make sure to change `extension.meta.xml` to select the correct Symphony versions, too.

**Comment by timokleemann** [comment]
Done.
